P2p java
couchbaselabs/mobile-testapps pull request #21
Opened 2020-10-01 21:30 UTC by mgcouchbase

2020-10-04 04:03 UTC, euniceatcouchbase requested changes

2020-10-05 18:16 UTC, mgcouchbase commented on CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/ListenerAuthenticatorRequestHandler.java
> +//        listenerPasswordAuthenticator.authenticate(username, password);
done

2020-10-08 23:53 UTC, euniceatcouchbase approved these changes

2020-10-09 00:51 UTC, sridevi-15 approved these changes

2020-10-09 00:51 UTC, merged