fixing certs issue on dotnet ios build
couchbaselabs/mobile-testapps pull request #25
Opened 2020-11-17 06:31 UTC by mgcouchbase

2020-11-17 17:32 UTC, sridevi-15 requested changes

2020-11-17 17:32 UTC, sridevi-15 commented on CBLClient/Apps/CBLTestServer-Dotnet/TestServer.iOS/TestServer.iOS.csproj
> +    <CodesignKey>Apple Development: James Borden (8538L9XTA3)</CodesignKey>
can you replace with mobille-team apple account? we need to make sure it works with mobile-team apple account

2020-11-23 16:56 UTC, euniceatcouchbase approved these changes

2021-02-25 21:46 UTC, sridevi-15 approved these changes

2021-02-25 21:50 UTC, merged